add_newline = true

format = """
$directory$git_branch$git_status
$character"""

# -------- Left info --------

[directory]
style = "green"
format = "$path "

truncate_to_repo = false

[git_branch]
symbol = ""
style = "green"
format = "[on $branch] "

[git_status]
style = "green"
format = "[$all_status$ahead_behind] "

# -------- Prompt char --------

[character]
success_symbol = "[>](bold green) "
error_symbol = "[>](bold red) "
